bump pmdsky-debug
SkyTemple/skytemple-files pull request #506
Opened 2024-05-31 08:01 UTC by theCapypara

Some symbols were renamed, this still needs to be fixed, and other SkyTemple sources must be checked as well.

2024-06-13 12:37 UTC, End45 requested changes

2024-06-13 12:37 UTC, End45 commented on skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py
> +        "",
```suggestion
        None,
```
As stated in the description of `Symbol`: "C type of this symbol. Empty string if unknown. None for functions."

2024-06-13 12:37 UTC, End45 commented on skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py
> +        "",
```suggestion
        None,
```
See above.

2024-06-13 12:37 UTC, End45 commented on skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py
> +    DebugPrint2 = Symbol(None, None, None, "DebugPrint2", DEBUG_PRINT2_DESC, "")
```suggestion
    DebugPrint2 = Symbol(None, None, None, "DebugPrint2", DEBUG_PRINT2_DESC, None)
```
See above.

2024-06-13 15:20 UTC, theCapypara commented
Thanks

2024-06-14 15:11 UTC, End45 approved these changes

2024-06-15 13:30 UTC, merged