FixNo$GbaSaves 0.2.0
SkyTemple/skytemple-files pull request #556
Opened 2024-12-14 02:30 UTC by Chesyon

2024-12-14 18:05 UTC, Frostbyte0x70 reviewed
Looks good!
The PR on my repo needs to be merged first, then the submodule needs to be updated. I'll approve once those two things are done.

2024-12-14 18:05 UTC, Frostbyte0x70 commented on skytemple_files/patch/handler/fix_nocash_saves.py
> +        return "0.2.0"
You know, since this patch now fully works with no side effects, why don't we bump it to v1.0 instead?

2024-12-15 21:03 UTC, Chesyon commented
Some kind of check needs to be added for the ExtraSpace version; this patch crashes the game on boot on old ExtraSpace versions, because ExtraSpace isn't loaded early enough for the first hook in those versions.

2024-12-16 16:26 UTC, Frostbyte0x70 commented
> Some kind of check needs to be added for the ExtraSpace version; this patch crashes the game on boot on old ExtraSpace versions, because ExtraSpace isn't loaded early enough for the first hook in those versions.

Hm... you're right. SkyTemple does not allow setting a minimum version of another patch as a dependency though, so not sure how this could be added.

2024-12-16 16:34 UTC, Chesyon commented
> Hm... you're right. SkyTemple does not allow setting a minimum version of another patch as a dependency though, so not sure how this could be added.
>
It would be kind of janky, but we could perhaps run a secondary is_applied check for the latest ExtraSpace version in patch.py, and prompt the user to reapply ExtraSpace if the check fails. I don't really know how to add prompts to the patch.py, though, so I might need some help in this regard.

2024-12-20 20:34 UTC, theCapypara commented
@Chesyon Some checks are failing.

2024-12-20 20:35 UTC, theCapypara requested changes
- Check for ExtraSpace version needs to be implemented
- Checks are failing

2024-12-20 23:04 UTC, Chesyon commented
> * Check for ExtraSpace version needs to be implemented
> 
>     * Checks are failing
> 
>     * The submodule needs to be updated

My code isn't finished; Frostbyte volunteered to implement the prompt. Once the prompt is added, the checks _should_ pass;  it's only currently failing because there's nothing inside the if statement, causing Python's complaining about indents. The ExtraSpace version check is implemented; all we're waiting on is the prompt from Frostbyte.

2024-12-21 11:44 UTC, closed without merging

2024-12-21 11:45 UTC, Frostbyte0x70 commented
Huh? Why did that get closed? Did I screw something up when pushing?

2024-12-21 11:46 UTC, theCapypara commented
You force-pushed Chesyon:master to be the same as skytemple-files:master

2024-12-21 11:50 UTC, Frostbyte0x70 commented
I was trying to push my local branch to chesyon:master
I guess Git didn't like that they had different names and pushed master instead
Oh well, new PR here: https://github.com/SkyTemple/skytemple-files/pull/558